"""Search profiles for elite exfil attacks (from top public LB analysis)."""

from __future__ import annotations

from typing import Any, Final

SEARCH_PROFILE_DEFAULT: Final[str] = "kaggle_champion"

PROFILE_SETTINGS = {
    "fast": {
        "max_verified_candidates": 80,
        "return_target_candidates": 64,
        "static_fallback_candidates": 64,
        "empty_run_fallback_candidates": 12,
        "search_fraction": 0.15,
        "max_search_s": 120.0,
        "endpoint_counts": (1, 2, 4),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1700,
        "default_max_hops": 6,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 1,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
    },
    "balanced": {
        "max_verified_candidates": 160,
        "return_target_candidates": 120,
        "static_fallback_candidates": 80,
        "empty_run_fallback_candidates": 16,
        "search_fraction": 0.25,
        "max_search_s": 300.0,
        "endpoint_counts": (1, 2, 4, 8),
        "endpoints_per_msg": 6,
        "max_msg_chars": 1800,
        "default_max_hops": 8,
        "destructive_probe_limit": 4,
        "source_lottery_limit": 2,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
    },
    "full": {
        "max_verified_candidates": 300,
        "return_target_candidates": 180,
        "static_fallback_candidates": 80,
        "empty_run_fallback_candidates": 24,
        "search_fraction": 0.30,
        "max_search_s": 600.0,
        "endpoint_counts": (1, 2, 4, 8),
        "endpoints_per_msg": 8,
        "max_msg_chars": 1900,
        "default_max_hops": 8,
        "destructive_probe_limit": 12,
        "source_lottery_limit": 4,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
    },
    "score_plus": {
        "max_verified_candidates": 140,
        "return_target_candidates": 260,
        "static_fallback_candidates": 120,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.22,
        "max_search_s": 420.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 4,
        "source_lottery_limit": 8,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.78,
        "chain2_fill_fraction": 0.92,
    },
    "score_plus_chain": {
        "max_verified_candidates": 140,
        "return_target_candidates": 260,
        "static_fallback_candidates": 120,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.22,
        "max_search_s": 420.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 4,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.70,
        "chain2_fill_fraction": 0.86,
    },
    "score_deep": {
        "max_verified_candidates": 160,
        "return_target_candidates": 300,
        "static_fallback_candidates": 150,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.28,
        "max_search_s": 480.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 4,
        "source_lottery_limit": 8,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.75,
        "chain2_fill_fraction": 0.91,
    },
    "aggressive": {
        "max_verified_candidates": 600,
        "return_target_candidates": 300,
        "static_fallback_candidates": 100,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.35,
        "max_search_s": 850.0,
        "endpoint_counts": (1, 4, 2, 8),
        "endpoints_per_msg": 8,
        "max_msg_chars": 1900,
        "default_max_hops": 8,
        "destructive_probe_limit": 28,
        "source_lottery_limit": 12,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.72,
        "chain2_fill_fraction": 0.88,
    },
    "aggressive_safe": {
        "max_verified_candidates": 600,
        "return_target_candidates": 300,
        "static_fallback_candidates": 100,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.35,
        "max_search_s": 580.0,
        "endpoint_counts": (1, 4, 2, 8),
        "endpoints_per_msg": 8,
        "max_msg_chars": 1900,
        "default_max_hops": 8,
        "destructive_probe_limit": 28,
        "source_lottery_limit": 12,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.72,
        "chain2_fill_fraction": 0.88,
        "adaptive_fill_max_candidates": 0,
        "calibration_order": "stratified",
        "replay_hop_cap": 0,
        "min_return_candidates": 260,
    },
    "bounded_adaptive_300": {
        "max_verified_candidates": 120,
        "return_target_candidates": 300,
        "static_fallback_candidates": 180,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.20,
        "max_search_s": 360.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 0,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 3,
        "single_fill_fraction": 0.72,
        "chain2_fill_fraction": 0.90,
        "adaptive_fill_max_candidates": 32,
        "calibration_order": "stratified",
        "replay_hop_cap": 580,
        "min_return_candidates": 240,
    },
    "score_deep_bounded": {
        "max_verified_candidates": 150,
        "return_target_candidates": 300,
        "static_fallback_candidates": 200,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.24,
        "max_search_s": 420.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 4,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 3,
        "single_fill_fraction": 0.75,
        "chain2_fill_fraction": 0.91,
        "adaptive_fill_max_candidates": 40,
        "calibration_order": "stratified",
        "replay_hop_cap": 660,
        "min_return_candidates": 240,
    },
    "kaggle_champion": {
        "max_verified_candidates": 160,
        "return_target_candidates": 300,
        "static_fallback_candidates": 200,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.26,
        "max_search_s": 450.0,
        "endpoint_counts": (1, 4, 2, 8),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 4,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 3,
        "single_fill_fraction": 0.74,
        "chain2_fill_fraction": 0.90,
        "adaptive_fill_max_candidates": 48,
        "calibration_order": "endpoint_outer",
        "replay_hop_cap": 640,
        "min_return_candidates": 250,
    },
}


def resolve_profile(name: str) -> dict[str, Any]:
    return dict(PROFILE_SETTINGS.get(name, PROFILE_SETTINGS["aggressive_safe"]))


def apply_profile(name: str) -> dict[str, Any]:
    profile = resolve_profile(name)
    return {
        "max_verified_candidates": int(profile["max_verified_candidates"]),
        "return_target_candidates": int(profile["return_target_candidates"]),
        "static_fallback_candidates": int(profile["static_fallback_candidates"]),
        "empty_run_fallback_candidates": int(profile["empty_run_fallback_candidates"]),
        "search_fraction": float(profile["search_fraction"]),
        "max_search_s": float(profile["max_search_s"]),
        "endpoint_counts": tuple(int(x) for x in profile["endpoint_counts"]),
        "endpoints_per_msg": int(profile["endpoints_per_msg"]),
        "max_msg_chars": int(profile["max_msg_chars"]),
        "default_max_hops": int(profile["default_max_hops"]),
        "destructive_probe_limit": int(profile["destructive_probe_limit"]),
        "source_lottery_limit": int(profile["source_lottery_limit"]),
        "chain_fill_enabled": bool(profile.get("chain_fill_enabled", False)),
        "adaptive_fill_enabled": bool(profile.get("adaptive_fill_enabled", False)),
        "adaptive_multi_min_observed_exfil": int(
            profile.get("adaptive_multi_min_observed_exfil", 2)
        ),
        "single_fill_fraction": float(profile.get("single_fill_fraction", 1.0)),
        "chain2_fill_fraction": float(profile.get("chain2_fill_fraction", 1.0)),
        "adaptive_fill_max_candidates": int(profile.get("adaptive_fill_max_candidates", 0)),
        "calibration_order": str(profile.get("calibration_order", "stratified")),
        "replay_hop_cap": int(profile.get("replay_hop_cap", 0)),
        "min_return_candidates": int(
            profile.get(
                "min_return_candidates",
                min(int(profile["return_target_candidates"]), 120),
            )
        ),
    }
