"""Search profiles for elite exfil attacks (from top public LB analysis)."""

from __future__ import annotations

from typing import Any, Final

SEARCH_PROFILE_DEFAULT: Final[str] = "guide28_static980_c1"

PROFILE_SETTINGS = {
    "fast": {
        "max_verified_candidates": 80,
        "return_target_candidates": 64,
        "static_fallback_candidates": 64,
        "empty_run_fallback_candidates": 12,
        "search_fraction": 0.15,
        "max_search_s": 120.0,
        "endpoint_counts": (1, 2, 4),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1700,
        "default_max_hops": 6,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 1,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
    },
    "balanced": {
        "max_verified_candidates": 160,
        "return_target_candidates": 120,
        "static_fallback_candidates": 80,
        "empty_run_fallback_candidates": 16,
        "search_fraction": 0.25,
        "max_search_s": 300.0,
        "endpoint_counts": (1, 2, 4, 8),
        "endpoints_per_msg": 6,
        "max_msg_chars": 1800,
        "default_max_hops": 8,
        "destructive_probe_limit": 4,
        "source_lottery_limit": 2,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
    },
    "full": {
        "max_verified_candidates": 300,
        "return_target_candidates": 180,
        "static_fallback_candidates": 80,
        "empty_run_fallback_candidates": 24,
        "search_fraction": 0.30,
        "max_search_s": 600.0,
        "endpoint_counts": (1, 2, 4, 8),
        "endpoints_per_msg": 8,
        "max_msg_chars": 1900,
        "default_max_hops": 8,
        "destructive_probe_limit": 12,
        "source_lottery_limit": 4,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
    },
    "score_plus": {
        "max_verified_candidates": 140,
        "return_target_candidates": 260,
        "static_fallback_candidates": 120,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.22,
        "max_search_s": 420.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 4,
        "source_lottery_limit": 8,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.78,
        "chain2_fill_fraction": 0.92,
    },
    "score_plus_chain": {
        "max_verified_candidates": 140,
        "return_target_candidates": 260,
        "static_fallback_candidates": 120,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.22,
        "max_search_s": 420.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 4,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.70,
        "chain2_fill_fraction": 0.86,
    },
    "score_deep": {
        "max_verified_candidates": 160,
        "return_target_candidates": 300,
        "static_fallback_candidates": 150,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.28,
        "max_search_s": 480.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 4,
        "source_lottery_limit": 8,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.75,
        "chain2_fill_fraction": 0.91,
    },
    "aggressive": {
        "max_verified_candidates": 600,
        "return_target_candidates": 300,
        "static_fallback_candidates": 100,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.35,
        "max_search_s": 850.0,
        "endpoint_counts": (1, 4, 2, 8),
        "endpoints_per_msg": 8,
        "max_msg_chars": 1900,
        "default_max_hops": 8,
        "destructive_probe_limit": 28,
        "source_lottery_limit": 12,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.72,
        "chain2_fill_fraction": 0.88,
    },
    "aggressive_safe": {
        "max_verified_candidates": 600,
        "return_target_candidates": 300,
        "static_fallback_candidates": 100,
        "empty_run_fallback_candidates": 32,
        "search_fraction": 0.35,
        "max_search_s": 580.0,
        "endpoint_counts": (1, 4, 2, 8),
        "endpoints_per_msg": 8,
        "max_msg_chars": 1900,
        "default_max_hops": 8,
        "destructive_probe_limit": 28,
        "source_lottery_limit": 12,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 0.72,
        "chain2_fill_fraction": 0.88,
        "adaptive_fill_max_candidates": 0,
        "calibration_order": "stratified",
        "replay_hop_cap": 0,
        "min_return_candidates": 260,
    },
    "bounded_adaptive_300": {
        "max_verified_candidates": 120,
        "return_target_candidates": 300,
        "static_fallback_candidates": 180,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.20,
        "max_search_s": 360.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 0,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 3,
        "single_fill_fraction": 0.72,
        "chain2_fill_fraction": 0.90,
        "adaptive_fill_max_candidates": 32,
        "calibration_order": "stratified",
        "replay_hop_cap": 580,
        "min_return_candidates": 240,
    },
    "score_deep_bounded": {
        "max_verified_candidates": 150,
        "return_target_candidates": 300,
        "static_fallback_candidates": 200,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.24,
        "max_search_s": 420.0,
        "endpoint_counts": (1, 4, 2),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 4,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 3,
        "single_fill_fraction": 0.75,
        "chain2_fill_fraction": 0.91,
        "adaptive_fill_max_candidates": 40,
        "calibration_order": "stratified",
        "replay_hop_cap": 660,
        "min_return_candidates": 240,
    },
    "kaggle_champion": {
        "max_verified_candidates": 160,
        "return_target_candidates": 300,
        "static_fallback_candidates": 200,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.26,
        "max_search_s": 450.0,
        "endpoint_counts": (1, 4, 2, 8),
        "endpoints_per_msg": 4,
        "max_msg_chars": 1900,
        "default_max_hops": 4,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 4,
        "chain_fill_enabled": True,
        "adaptive_fill_enabled": True,
        "adaptive_multi_min_observed_exfil": 3,
        "single_fill_fraction": 0.74,
        "chain2_fill_fraction": 0.90,
        "adaptive_fill_max_candidates": 48,
        "calibration_order": "endpoint_outer",
        "replay_hop_cap": 640,
        "min_return_candidates": 250,
    },
    # Replay-dense static fill (Pilkwang guide24 ~55.8 LB, Yaroslav guide26 ~55.8)
    "guide24_static620_c1": {
        "max_verified_candidates": 1,
        "return_target_candidates": 620,
        "static_fallback_candidates": 620,
        "empty_run_fallback_candidates": 620,
        "search_fraction": 0.0,
        "max_search_s": 0.0,
        "endpoint_counts": (1,),
        "endpoints_per_msg": 1,
        "max_msg_chars": 140,
        "default_max_hops": 1,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 0,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
        "adaptive_fill_max_candidates": 0,
        "calibration_order": "stratified",
        "replay_hop_cap": 0,
        "min_return_candidates": 620,
        "calibration_fraction": 0.0,
        "mutation_fraction": 0.0,
        "mass_fraction": 0.0,
        "single_fraction": 0.0,
        "deputy_fraction": 0.0,
        "destructive_fraction": 0.0,
        "combo_pool_size": 1,
        "fill_pool_size": 1,
        "mutation_seed_limit": 0,
        "snapshot_branch_limit": 0,
        "deputy_probe_limit": 0,
        "deputy_mutation_limit": 0,
        "safe_target_factor": 0.70,
    },
    "guide26_static700_c1": {
        "max_verified_candidates": 1,
        "return_target_candidates": 700,
        "static_fallback_candidates": 700,
        "empty_run_fallback_candidates": 700,
        "search_fraction": 0.0,
        "max_search_s": 0.0,
        "endpoint_counts": (1,),
        "endpoints_per_msg": 1,
        "max_msg_chars": 140,
        "default_max_hops": 1,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 0,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
        "adaptive_fill_max_candidates": 0,
        "calibration_order": "stratified",
        "replay_hop_cap": 0,
        "min_return_candidates": 700,
        "calibration_fraction": 0.0,
        "mutation_fraction": 0.0,
        "mass_fraction": 0.0,
        "single_fraction": 0.0,
        "deputy_fraction": 0.0,
        "destructive_fraction": 0.0,
        "combo_pool_size": 1,
        "fill_pool_size": 1,
        "mutation_seed_limit": 0,
        "snapshot_branch_limit": 0,
        "deputy_probe_limit": 0,
        "deputy_mutation_limit": 0,
        "safe_target_factor": 0.70,
    },
    # Target ~93 LB: ~980 single-hop exfil candidates (Kohei-tier volume)
    "guide28_static980_c1": {
        "max_verified_candidates": 1,
        "return_target_candidates": 980,
        "static_fallback_candidates": 980,
        "empty_run_fallback_candidates": 980,
        "search_fraction": 0.0,
        "max_search_s": 0.0,
        "endpoint_counts": (1,),
        "endpoints_per_msg": 1,
        "max_msg_chars": 140,
        "default_max_hops": 1,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 0,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
        "adaptive_fill_max_candidates": 0,
        "calibration_order": "stratified",
        "replay_hop_cap": 0,
        "min_return_candidates": 980,
        "calibration_fraction": 0.0,
        "mutation_fraction": 0.0,
        "mass_fraction": 0.0,
        "single_fraction": 0.0,
        "deputy_fraction": 0.0,
        "destructive_fraction": 0.0,
        "combo_pool_size": 1,
        "fill_pool_size": 1,
        "mutation_seed_limit": 0,
        "snapshot_branch_limit": 0,
        "deputy_probe_limit": 0,
        "deputy_mutation_limit": 0,
        "safe_target_factor": 0.70,
    },
    # Karnak single_900: minimal search + max single-post volume
    "single_900": {
        "max_verified_candidates": 60,
        "return_target_candidates": 900,
        "static_fallback_candidates": 450,
        "empty_run_fallback_candidates": 40,
        "search_fraction": 0.04,
        "max_search_s": 60.0,
        "endpoint_counts": (1,),
        "endpoints_per_msg": 1,
        "max_msg_chars": 260,
        "default_max_hops": 1,
        "destructive_probe_limit": 0,
        "source_lottery_limit": 0,
        "chain_fill_enabled": False,
        "adaptive_fill_enabled": False,
        "adaptive_multi_min_observed_exfil": 2,
        "single_fill_fraction": 1.00,
        "chain2_fill_fraction": 1.00,
        "adaptive_fill_max_candidates": 0,
        "calibration_order": "stratified",
        "replay_hop_cap": 0,
        "min_return_candidates": 620,
        "calibration_fraction": 0.20,
        "mutation_fraction": 0.30,
        "mass_fraction": 0.80,
        "single_fraction": 0.95,
        "deputy_fraction": 0.97,
        "destructive_fraction": 0.99,
        "combo_pool_size": 6,
        "fill_pool_size": 30,
        "mutation_seed_limit": 3,
        "snapshot_branch_limit": 0,
        "deputy_probe_limit": 0,
        "deputy_mutation_limit": 0,
        "safe_target_factor": 0.70,
    },
}


def resolve_profile(name: str) -> dict[str, Any]:
    return dict(PROFILE_SETTINGS.get(name, PROFILE_SETTINGS["aggressive_safe"]))


def apply_profile(name: str) -> dict[str, Any]:
    profile = resolve_profile(name)
    return {
        "max_verified_candidates": int(profile["max_verified_candidates"]),
        "return_target_candidates": int(profile["return_target_candidates"]),
        "static_fallback_candidates": int(profile["static_fallback_candidates"]),
        "empty_run_fallback_candidates": int(profile["empty_run_fallback_candidates"]),
        "search_fraction": float(profile["search_fraction"]),
        "max_search_s": float(profile["max_search_s"]),
        "endpoint_counts": tuple(int(x) for x in profile["endpoint_counts"]),
        "endpoints_per_msg": int(profile["endpoints_per_msg"]),
        "max_msg_chars": int(profile["max_msg_chars"]),
        "default_max_hops": int(profile["default_max_hops"]),
        "destructive_probe_limit": int(profile["destructive_probe_limit"]),
        "source_lottery_limit": int(profile["source_lottery_limit"]),
        "chain_fill_enabled": bool(profile.get("chain_fill_enabled", False)),
        "adaptive_fill_enabled": bool(profile.get("adaptive_fill_enabled", False)),
        "adaptive_multi_min_observed_exfil": int(
            profile.get("adaptive_multi_min_observed_exfil", 2)
        ),
        "single_fill_fraction": float(profile.get("single_fill_fraction", 1.0)),
        "chain2_fill_fraction": float(profile.get("chain2_fill_fraction", 1.0)),
        "adaptive_fill_max_candidates": int(profile.get("adaptive_fill_max_candidates", 0)),
        "calibration_order": str(profile.get("calibration_order", "stratified")),
        "replay_hop_cap": int(profile.get("replay_hop_cap", 0)),
        "min_return_candidates": int(
            profile.get(
                "min_return_candidates",
                min(int(profile["return_target_candidates"]), 120),
            )
        ),
        "calibration_fraction": float(profile.get("calibration_fraction", 0.22)),
        "mutation_fraction": float(profile.get("mutation_fraction", 0.38)),
        "mass_fraction": float(profile.get("mass_fraction", 0.78)),
        "single_fraction": float(profile.get("single_fraction", 0.88)),
        "deputy_fraction": float(profile.get("deputy_fraction", 0.94)),
        "destructive_fraction": float(profile.get("destructive_fraction", 0.975)),
        "combo_pool_size": max(1, int(profile.get("combo_pool_size", 8))),
        "fill_pool_size": max(1, int(profile.get("fill_pool_size", 12))),
        "mutation_seed_limit": max(0, int(profile.get("mutation_seed_limit", 12))),
        "snapshot_branch_limit": max(0, int(profile.get("snapshot_branch_limit", 3))),
        "deputy_probe_limit": max(0, int(profile.get("deputy_probe_limit", 12))),
        "deputy_mutation_limit": max(0, int(profile.get("deputy_mutation_limit", 6))),
        "safe_target_factor": float(profile.get("safe_target_factor", 0.7)),
    }
